version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Specify FastAPI Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  selenium_worker:
    build:
      context: .
      dockerfile: Dockerfile.selenium  # Specify Selenium Worker Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 3  # Number of concurrent Selenium clients
