version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=car_alerts  # Add this if used in config

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  selenium_worker:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=car_alerts  # Add this if used in config
    depends_on:
      - redis
    deploy:
      replicas: 3  # Number of concurrent Selenium clients
